theme = "catppuccin_macchiato"

[editor]
bufferline = "multiple"
color-modes = true
line-number = "relative"
mouse = false
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"

[editor.indent-guides]
render = true
character = "╎"

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
g = { a = "code_action" }
esc = ["collapse_selection", "keep_primary_selection"]