brew "asdf"
brew "bat"
brew "bottom"
brew "exa"
brew "fd"
brew "flyctl"
brew "git"
brew "httpie"
brew "jq"
brew "lazygit"
brew "neovim", args: ["HEAD"]
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "sd"
brew "starship"
brew "stylua"
brew "tmux"
brew "tree"
brew "universal-ctags", args: ["HEAD"]
brew "wget"
