require("options")
require("keymaps")
require("plugins")
require("colorscheme")
require("lsp")
require("autocommands")

require("plugins.cmp")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.toggleterm")
require("plugins.indent_blankline")
require("plugins.which-key")
