require("sineraves.plugins-setup")

require("sineraves.core.options")
require("sineraves.core.keymaps")
require("sineraves.core.colorscheme")

require("sineraves.plugins.comment")
require("sineraves.plugins.gitsigns")
require("sineraves.plugins.inc-rename")
require("sineraves.plugins.indent-blankline")
require("sineraves.plugins.lualine")
require("sineraves.plugins.luasnip")
require("sineraves.plugins.nvim-autopairs")
require("sineraves.plugins.nvim-cmp")
require("sineraves.plugins.nvim-dap")
require("sineraves.plugins.nvim-dap-ui")
require("sineraves.plugins.nvim-notify")
require("sineraves.plugins.nvim-tree")
require("sineraves.plugins.telescope")
require("sineraves.plugins.treesitter")
require("sineraves.plugins.vim-sandwich")
require("sineraves.plugins.vim-test")
require("sineraves.plugins.which-key")

require("sineraves.plugins.lsp.mason")
require("sineraves.plugins.lsp.lspconfig")
require("sineraves.plugins.lsp.null-ls")
