require("plugins.packer")

require("plugins.cmp")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.vim-test")
require("plugins.which-key")
